export const HOTEL_CATEGORIES = [
  '1 Star',
  '2 Star',
  '3 Star',
  '4 Star',
  '5 Star',
  'Homestay',
  'Guest House',
  'Villa',
  'Cottage',
  'Camp',
  'Tent',
  'Houseboat',
  'Tree House',
  'Farm Stay',
  'Boutique Hotel',
  'Palace Hotel',
  'Lodge',
  'Apartment',
  'Serviced Apartment',
  'Cabin',
  'Bungalow',
  'Eco Lodge / Eco Resort',
  'Jungle Lodge',
  'Beach Hut',
  'Mountain Hut',
  'Ashram / Retreat',
  'Monastery Stay',
  'Ranch / Farmhouse',
  'Caravan / Campervan',
];
